apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q9cf4uuwo-nodejs
  janus-idp.io/tekton: q9cf4uuwo-nodejs
  backstage.io/kubernetes-id: q9cf4uuwo-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q9cf4uuwo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
